version: '3.7'
services:
  webapp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'development'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    
  webapp-ci:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'production'
      
